
language: node_js
node_js:
  - "12"
dist: trusty
sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
  - master

cache:
  directories:
    - ./node_modules

install:
  - npm install -g yarn
  - yarn

jobs:
  include:
    - stage: Lint
      name: "Lint"
      script: yarn lint
    - stage: Test
      name: "Test"
      script: yarn test-headless
    - stage: Build
      name: "Build"
      script: yarn build